name: Pipeline CI/CD

on:
  push:
    branches:
      - feature/*
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: felipecampelo
          POSTGRES_PASSWORD: felipecampelo159753
          POSTGRES_DB: felipecampelo
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 18
        uses: actions/setup-node@v3

      - name: Build React frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      # Placeholder para testes do React no futuro
      # - name: Executar testes (React App)
      #   working-directory: ./frontend
      #   run: npm test

      - name: Sanity testing on Directus
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://localhost:8055/server/health | grep ok
